_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: fi
ignored_config_entities:
  - hdbt_admin_tools.site_settings
  - 'system.site:page.front'
  - 'hdbt_admin_tools.site_settings:site_settings'
  - 'easy_breadcrumb.settings:home_segment_title'
