_core:
  default_config_hash: 1oYqGyOsIZHGnNlHydDMMxwW3GyI96gK8lvrYPHwphM
features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: false
  path: ''
