<?php

/**
 * @file
 * Contains alterations for config.
 */

declare(strict_types=1);

use Drupal\config_rewrite\ConfigRewriterInterface;

/**
 * Implements hook_rewrite_config_update().
 */
function helfi_emergency_config_rewrite_config_update(string $module, ConfigRewriterInterface $configRewriter): void {
  $modules = [
    'helfi_eu_cookie_compliance',
    'helfi_media_chart',
    'helfi_media_remote_video',
    'helfi_node_news_item',
  ];

  if (in_array($module, $modules)) {
    // Rewrite module configuration.
    $configRewriter->rewriteModuleConfig('helfi_emergency_config');
  }
}
