config_rewrite:
  replace: ['hidden']
content:
  field_is_crisis_news:
    type: boolean
    label: above
    settings:
      format: default
      format_custom_false: ''
      format_custom_true: ''
    third_party_settings: {  }
    weight: 2
    region: content
hidden:
  field_news_item_tags: true
  langcode: true
  toc_enabled: true
