config_rewrite:
  replace: ['dependencies.module']
dependencies:
  module:
    - content_translation
third_party_settings:
  content_translation:
    bundle_settings:
      untranslatable_fields_hide: '0'
